(()=>{
const $=id=>document.getElementById(id),battle=$('battle'),scene=$('scene'),player=$('player'),arrow=$('arrow'),joy=$('joy'),knob=$('knob'),A=$('A'),B=$('B'),X=$('X'),Y=$('Y');
const FIELD=window.BattleNetworkField,RANGE=window.BattleNetworkRangeGeometry,RANGE_PREVIEW=window.BattleNetworkRangePreview,BOMB_PREVIEW=window.BattleNetworkBombPreview,B_ATTACK=window.BattleNetworkBAttack,P_SHADOW=window.BattleNetworkProjectileShadow,B_PROJECTILE=window.BattleNetworkBusterProjectile,ENEMY=window.BattleNetworkEnemy,PLAYER_HEALTH=window.BattleNetworkPlayerHealth,PARAMS=window.BattleNetworkParameters;
if(!FIELD)throw new Error('BattleNetwork: logical field grid is not loaded.');
if(!RANGE||!RANGE_PREVIEW||!BOMB_PREVIEW)throw new Error('BattleNetwork: combat range system is not loaded.');
if(!B_ATTACK)throw new Error('BattleNetwork: B attack system is not loaded.');
if(!P_SHADOW)throw new Error('BattleNetwork: projectile shadow system is not loaded.');
if(!B_PROJECTILE)throw new Error('BattleNetwork: buster projectile layer is not loaded.');
if(!ENEMY)throw new Error('BattleNetwork: enemy foundation is not loaded.');
if(!PLAYER_HEALTH)throw new Error('BattleNetwork: player health is not loaded.');
if(!PARAMS)throw new Error('BattleNetwork: parameter system is not loaded.');
const WORLD=FIELD.WORLD_SIZE,PX=.72,PY=.36,SW=WORLD*PX*2,SH=WORLD*PY*2,DEAD=.12,FOLLOW=.14,CAMERA_ZOOM=.62,CUSTOM_TIME=10,LONG_PRESS_MS=520,HIT_STUN_MS=300;
const PLAYER_VISUAL=Object.freeze({width:108,height:136});
const PLAYER_HITBOX=Object.freeze({width:FIELD.TILE_SIZE*1.32,height:FIELD.TILE_SIZE*1.32,offsetX:0,offsetY:0});
const {CHIP,ATTR_IMAGE,ATTR_LABEL}=window.BattleNetworkMaster.createGameCompatibilityData();
const folder=[['CANNON','A'],['SWORD','S'],['WIDE','S'],['BOMB','B'],['RECOVER','A'],['CANNON','B'],['SWORD','E'],['WIDE','E'],['BOMB','L'],['RECOVER','L'],['CANNON','C'],['SWORD','S'],['WIDE','S'],['BOMB','*'],['RECOVER','A'],['CANNON','*'],['SWORD','E'],['WIDE','E'],['BOMB','B'],['RECOVER','L'],['CANNON','A'],['SWORD','S'],['WIDE','S'],['BOMB','L'],['RECOVER','A'],['CANNON','B'],['SWORD','E'],['WIDE','E'],['BOMB','*'],['RECOVER','L']];
let uid=0;const cards=folder.map(([type,code])=>({id:uid++,type,code}));
const s={x:WORLD/2,y:WORLD/2,ix:0,iy:0,dx:1,dy:0,cx:0,cy:0,tileRow:null,tileCol:null,currentTile:null,currentTerrain:null,lastAttackRange:null,lastAttackContext:null,pendingChipAttack:null,pendingBurstShots:[],last:performance.now(),dash:0,dashRecharge:[],dashQueued:false,dvx:0,dvy:0,bHeld:false,bAt:0,charged:false,bTapAction:null,bHoldAction:null,bChargeTime:0,lastShot:-1e9,lock:0,hitStunUntil:0,defeated:false,directionLocked:false,paused:true,custom:0,customReady:false,queue:[],draw:[],discard:new Set(),hand:[],selected:[]},bullets=[];
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t;
let editMode=false,menuOpen=false,customHiddenForSettings=false,previewMode='none';
let battleWidth=0,battleHeight=0,activeJoyRect=null;
const defaults={left:{x:18,bottom:16,scale:1,opacity:1},A:{right:82,bottom:16,scale:1,opacity:1},B:{right:8,bottom:88,scale:1,opacity:1},X:{right:156,bottom:88,scale:1,opacity:1},Y:{right:82,bottom:160,scale:1,opacity:1}};
let controlSettings=loadSettings(),selectedKey=null,editPointers=new Map(),gesture=null;
const elements={left:joy,A,B,X,Y},names={left:'左スティック',A:'Aボタン',B:'Bボタン',X:'Xボタン',Y:'Yボタン'};
function cloneDefaults(){return JSON.parse(JSON.stringify(defaults))}
function loadSettings(){try{const v=JSON.parse(localStorage.getItem('battleNetworkControlsV3'));return v&&v.left&&v.A&&v.B&&v.X&&v.Y?v:cloneDefaults()}catch{return cloneDefaults()}}
function saveSettings(){localStorage.setItem('battleNetworkControlsV3',JSON.stringify(controlSettings))}
function refreshBattleSize(){battleWidth=battle.clientWidth;battleHeight=battle.clientHeight}
function applyControls(){const l=controlSettings.left;joy.style.left=l.x+'px';joy.style.bottom=l.bottom+'px';joy.style.transform=`scale(${l.scale})`;joy.style.opacity=l.opacity;['A','B','X','Y'].forEach(k=>{const el=elements[k],v=controlSettings[k];el.style.right=v.right+'px';el.style.bottom=v.bottom+'px';el.style.transform=`scale(${v.scale})`;el.style.opacity=v.opacity});activeJoyRect=null;updateSelectionLabel()}
function proj(x,y){return{x:(x-y)*PX+SW/2,y:(x+y)*PY}}
function angle(dx,dy){return Math.atan2((dx+dy)*PY,(dx-dy)*PX)*180/Math.PI}
function unit(dx,dy){let x=(dx-dy)*PX,y=(dx+dy)*PY,l=Math.hypot(x,y)||1;return{x:x/l,y:y/l}}
function camera(){let p=proj(s.x,s.y),vw=battleWidth/CAMERA_ZOOM,vh=battleHeight/CAMERA_ZOOM;return{x:clamp(p.x-vw/2,0,SW-vw),y:clamp(p.y-vh*.58,0,SH-vh)}}
function playerParams(){return PARAMS.getEffective('player')}
function updatePlayerTile(){let tile=FIELD.getTileAtWorld(s.x,s.y);if(!tile)return;let changed=s.tileRow!==tile.row||s.tileCol!==tile.col||s.currentTerrain!==tile.currentTerrain;s.currentTile=tile;if(!changed)return;s.tileRow=tile.row;s.tileCol=tile.col;s.currentTerrain=tile.currentTerrain;player.dataset.tileRow=String(tile.row);player.dataset.tileCol=String(tile.col);player.dataset.terrain=tile.currentTerrain}
function getPlayerBoundsAt(x=s.x,y=s.y){let centerX=x+PLAYER_HITBOX.offsetX,centerY=y+PLAYER_HITBOX.offsetY,halfW=PLAYER_HITBOX.width/2,halfH=PLAYER_HITBOX.height/2;return Object.freeze({left:centerX-halfW,right:centerX+halfW,top:centerY-halfH,bottom:centerY+halfH,width:PLAYER_HITBOX.width,height:PLAYER_HITBOX.height,centerX,centerY})}
function getPlayerBounds(){return getPlayerBoundsAt(s.x,s.y)}
function playerContainsPoint(x,y){if(!Number.isFinite(x)||!Number.isFinite(y))return false;let b=getPlayerBounds();return x>=b.left&&x<=b.right&&y>=b.top&&y<=b.bottom}
function tryPlayerPosition(x,y){const nx=clamp(x,0,WORLD),ny=clamp(y,0,WORLD);if(ENEMY.isPlayerBoundsBlocked?.(getPlayerBoundsAt(nx,ny)))return false;if(FIELD.trackOccupant&&!FIELD.trackOccupant('player',nx,ny))return false;s.x=nx;s.y=ny;return true}
function tryPlayerDashPosition(x,y){const nx=clamp(x,0,WORLD),ny=clamp(y,0,WORLD);if(FIELD.trackOccupant&&!FIELD.trackOccupant('player',nx,ny))return false;s.x=nx;s.y=ny;return true}
function movePlayerWithCollision(dx,dy){if(!dx&&!dy)return;const targetX=clamp(s.x+dx,0,WORLD),targetY=clamp(s.y+dy,0,WORLD);if(tryPlayerPosition(targetX,targetY))return;if(dx){const nx=clamp(s.x+dx,0,WORLD);tryPlayerPosition(nx,s.y)}if(dy){const ny=clamp(s.y+dy,0,WORLD);tryPlayerPosition(s.x,ny)}}
function resolveDashEndCollision(){ENEMY.pushBlockingEnemiesFromBounds?.(getPlayerBounds(),{x:s.dvx,y:s.dvy})}
function buildChipRange(ch,origin={x:s.x,y:s.y},direction={x:s.dx,y:s.dy}){return RANGE.createFromChip(ch,{origin,direction})}
function buildBombRange(ch,origin={x:s.x,y:s.y},direction={x:s.dx,y:s.dy}){let dir=RANGE.normalizeDirection(direction),throwTiles=Number(ch?.throwDistanceTiles),distance=FIELD.toWorldDistance(Number.isFinite(throwTiles)?throwTiles:3),center={x:origin.x+dir.x*distance,y:origin.y+dir.y*distance};return RANGE.createCircle(center,ch?.radiusTiles??.75)}
function card(id){return cards.find(c=>c.id===id)}
function shuffle(a){for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function resetWave(){FIELD.resetTerrain?.();FIELD.trackOccupant?.('player',s.x,s.y);s.draw=shuffle(cards.map(c=>c.id));s.discard.clear();s.queue=[];s.custom=0;s.customReady=false;s.hand=[];openCustom(true)}
function nextHand(){s.hand=s.draw.slice(0,5);s.selected=[];renderCustom()}
function openCustom(initial=false){if(s.defeated)return;s.paused=true;joyReset();clearCharge();$('customModal').classList.add('open');if(initial||!s.hand.length)nextHand();else renderCustom();updateFooterChips()}
function validSelection(ids){if(ids.length<=1)return true;let cs=ids.map(card);if(cs.every(c=>c.type===cs[0].type))return true;return new Set(cs.filter(c=>c.code!=='*').map(c=>c.code)).size<=1}
function canAdd(id){return s.selected.includes(id)||validSelection([...s.selected,id])}
function attrHtml(type){let attr=CHIP[type].attr,src=ATTR_IMAGE[attr]||ATTR_IMAGE.normal,label=ATTR_LABEL[attr]||ATTR_LABEL.normal;return `<img class="attrIcon" src="${src}" alt="${label}" draggable="false">`}
function chipArtHtml(type){let src=CHIP[type].image;return src?`<img src="${src}" alt="${CHIP[type].name}" draggable="false">`:''}
function footerIds(){return $('customModal').classList.contains('open')&&s.selected.length?s.selected:s.queue}
function updateFooterChips(){$('chipNow').textContent='チップ';$('queue').innerHTML='';let ids=footerIds();if(!ids.length){let d=document.createElement('span');d.className='q empty';d.textContent='--';$('queue').appendChild(d);return}ids.forEach(id=>{let c=card(id),d=document.createElement('span');d.className='q';d.textContent=CHIP[c.type].name;$('queue').appendChild(d)})}
function showChipDetail(id){let c=card(id),ch=CHIP[c.type],attr=ATTR_LABEL[ch.attr]||ATTR_LABEL.normal;$('detailName').textContent=ch.name;$('detailArt').innerHTML=chipArtHtml(c.type);$('detailAttrIcon').innerHTML=attrHtml(c.type);$('detailAttr').textContent=attr;$('detailDesc').textContent=ch.detail;$('detailPower').textContent=ch.type==='recover'?`回復量：${ch.heal}`:`攻撃力：${ch.power}`;$('detailRangeText').textContent=ch.rangeText;$('detailRange').className='rangeViz '+ch.viz;$('chipDetailModal').classList.add('open');$('chipDetailModal').querySelector('.chipDetail').scrollTop=0}
function closeChipDetail(){$('chipDetailModal').classList.remove('open')}
$('detailClose').onclick=closeChipDetail;$('chipDetailModal').addEventListener('pointerdown',e=>{if(e.target===$('chipDetailModal'))closeChipDetail()});
function bindChipCard(b,id,ok){let timer=null,startX=0,startY=0,longPressed=false;const clear=()=>{if(timer){clearTimeout(timer);timer=null}};b.addEventListener('pointerdown',e=>{startX=e.clientX;startY=e.clientY;longPressed=false;clear();timer=setTimeout(()=>{timer=null;longPressed=true;showChipDetail(id)},LONG_PRESS_MS)});b.addEventListener('pointermove',e=>{if(Math.hypot(e.clientX-startX,e.clientY-startY)>12)clear()});b.addEventListener('pointerup',clear);b.addEventListener('pointercancel',clear);b.addEventListener('lostpointercapture',clear);b.addEventListener('click',e=>{if(longPressed){longPressed=false;e.preventDefault();e.stopPropagation();return}if(!ok)return;let i=s.selected.indexOf(id);i>=0?s.selected.splice(i,1):s.selected.push(id);renderCustom()})}
function renderCustom(){$('folderInfo').textContent=`フォルダ ${s.draw.length}`;$('hand').innerHTML='';for(let slot=0;slot<10;slot++){let id=s.hand[slot];if(id===undefined){let e=document.createElement('div');e.className='chipCard empty';e.innerHTML=`<span class="slotNo">${slot+1}</span><span class="chipName">---</span><span class="chipArt"></span><span class="chipMeta"><span class="chipCode">-</span><span class="chipAttr"></span><span class="chipValue">--</span></span>`;$('hand').appendChild(e);continue}let c=card(id),b=document.createElement('button'),ok=canAdd(id);b.className='chipCard'+(s.selected.includes(id)?' sel':'')+(!ok?' blocked':'');b.innerHTML=`<span class="slotNo">${slot+1}</span><span class="chipName">${CHIP[c.type].name}</span><span class="chipArt">${chipArtHtml(c.type)}</span><span class="chipMeta"><span class="chipCode">${c.code}</span><span class="chipAttr">${attrHtml(c.type)}</span><span class="chipValue">--</span></span>`;bindChipCard(b,id,ok);$('hand').appendChild(b)}updateFooterChips()}
$('send').onclick=()=>{if(s.selected.length){s.queue.forEach(id=>s.discard.add(id));let ss=new Set(s.selected);s.hand.forEach(id=>{let p=s.draw.indexOf(id);if(p>=0)s.draw.splice(p,1);if(!ss.has(id))s.discard.add(id)});s.queue=s.selected.slice()}s.hand=[];s.selected=[];s.custom=0;s.customReady=false;$('customModal').classList.remove('open');let waveState=window.BattleNetworkWave?.onCustomConfirmed?.();s.paused=waveState?.status==='STARTING';updateHud()};
function setPreviewMode(mode){if(previewMode===mode)return;previewMode=mode;if(mode==='none'){RANGE_PREVIEW.hide();BOMB_PREVIEW.hide()}else if(mode==='range'){BOMB_PREVIEW.hide()}}
function renderPreview(){if(s.defeated){setPreviewMode('none');return}if(!s.queue.length){setPreviewMode('none');return}let ch=CHIP[card(s.queue[0]).type];if(ch.type==='recover'){setPreviewMode('none');return}if(ch.type==='bomb'){let shape=buildBombRange(ch);setPreviewMode('bomb');RANGE_PREVIEW.render(shape);BOMB_PREVIEW.render({x:s.x,y:s.y},shape.center);return}let shape=buildChipRange(ch);if(shape&&(shape.rangeTypeId==='LINE'||shape.rangeTypeId==='RECT'||shape.rangeTypeId==='CIRCLE')){setPreviewMode('range');RANGE_PREVIEW.render(shape);return}setPreviewMode('none')}
function updateCustomGauge(){let pc=Math.min(s.custom,CUSTOM_TIME)/CUSTOM_TIME*100;$('customFill').style.width=pc+'%';$('customGauge').classList.toggle('ready',s.customReady&&!s.defeated);$('customGauge').setAttribute('aria-disabled',s.defeated||!s.customReady?'true':'false')}
function updateHud(){updateFooterChips();updateCustomGauge();renderPreview()}
function spawn(kind,range,speed,direction={x:s.dx,y:s.dy},damage=null,attackId=null){range=Number(range);speed=Number(speed);if(!(range>0)||!(speed>0))return;let d={x:direction.x,y:direction.y},l=Math.hypot(d.x,d.y)||1;d.x/=l;d.y/=l;let isBuster=kind==='normal'||kind==='charged'||kind==='vulcan',el=isBuster?B_PROJECTILE.create(kind):document.createElement('div');if(!el)return;let numericDamage=Number(damage),b={x:s.x,y:s.y,dx:d.x,dy:d.y,dist:0,range,speed,kind,damage:Number.isFinite(numericDamage)?numericDamage:null,attackId,layer:isBuster?'buster':'scene',el};if(!isBuster){b.el.className='bullet '+kind;scene.appendChild(b.el);P_SHADOW.attach(b.el,kind)}bullets.push(b)}
function hitBusterEnemy(b){let enemyId=ENEMY.findEnemyIdAtPoint(b.x,b.y);if(enemyId===null)return false;if(Number.isFinite(b.damage)&&b.damage>0)ENEMY.applyDamage(enemyId,b.damage);ENEMY.debugFlash(enemyId);return true}
function clearPlayerProjectiles(){for(let i=bullets.length-1;i>=0;i--){let b=bullets[i];if(b.layer==='buster')B_PROJECTILE.remove(b.el);else{P_SHADOW.detach(b.el);b.el.remove()}}bullets.length=0}
function effect(cls,x,y,w,h){let e=document.createElement('div');e.className=cls;e.style.cssText=`width:${w}px;height:${h}px;left:${x-w/2}px;top:${y-h/2}px`;scene.appendChild(e);setTimeout(()=>e.remove(),700)}
function setChipAttackContext(c,attackShape){s.lastAttackRange=attackShape;s.lastAttackContext=Object.freeze({shape:attackShape,sourceType:'CHIP',sourceId:c.chipId,damage:Number.isFinite(Number(c.power))?Number(c.power):null,shotToken:performance.now()+Math.random()})}
function fireLineProjectile(c,attackDirection,attackShape,kind='cannon'){setChipAttackContext(c,attackShape);let projectileRange=attackShape?.lengthWorld??c.range,firstHit=window.BattleNetworkCombatHitTest?.getFirstCannonHit?.({shape:attackShape});if(firstHit&&Number.isFinite(firstHit.distance))projectileRange=Math.min(projectileRange,firstHit.distance);spawn(kind,projectileRange,c.projectileSpeed||2000,attackDirection,null,`CHIP:${c.chipId}`)}
function firePendingBurstShot(shot){if(!shot||s.defeated)return;fireLineProjectile(shot.c,shot.attackDirection,shot.attackShape,'vulcan')}
function executeChipAttack(pending){if(!pending||s.defeated)return;let {c,attackDirection,attackOrigin,attackShape}=pending,p=proj(attackOrigin.x,attackOrigin.y),u=unit(attackDirection.x,attackDirection.y);if(c.type==='cannon'){fireLineProjectile(c,attackDirection,attackShape,'cannon')}else if(c.type==='vulcan'){let interval=Math.max(0,Number(c.burstIntervalSec)||0),count=Math.max(1,Math.floor(Number(c.burstCount)||3));fireLineProjectile(c,attackDirection,attackShape,'vulcan');s.pendingBurstShots=[];for(let i=1;i<count;i++)s.pendingBurstShots.push({c,attackDirection,attackShape,remaining:interval*i})}else{setChipAttackContext(c,attackShape);if(c.type==='sword'||c.type==='wide'){let range=attackShape?.lengthWorld??c.range,width=attackShape?.widthWorld??c.width;effect('slash',p.x+u.x*range*PX*.45,p.y-30+u.y*range*PX*.45,range*PX,width*PY)}else if(c.type==='bomb'){let center=attackShape?.center||attackOrigin,target=proj(center.x,center.y),radius=attackShape?.radiusWorld??c.radius;setTimeout(()=>effect('boom',target.x,target.y-30,radius*PX*2,radius*PX*2),(c.explosionDelay??.28)*1000)}else if(c.type==='recover'){PLAYER_HEALTH.applyHealing(c.heal);effect('healPulse',p.x,p.y-36,86,86)}}}
function useChip(){if(s.defeated||s.paused||s.dash>0||s.lock>0||isHitStunned()||!s.queue.length||editMode)return;let id=s.queue.shift(),c=CHIP[card(id).type];s.discard.add(id);let startup=Math.max(0,Number(c.startupDelay)||0),recovery=Math.max(0,Number(c.lock??.25)),burstDuration=c.type==='vulcan'?Math.max(0,Number(c.burstIntervalSec)||0)*Math.max(0,(Math.floor(Number(c.burstCount)||3)-1)):0;s.lock=startup+burstDuration+recovery;let attackDirection=RANGE.normalizeDirection({x:s.dx,y:s.dy}),attackOrigin={x:s.x,y:s.y},attackShape=c.type==='bomb'?buildBombRange(c,attackOrigin,attackDirection):buildChipRange(c,attackOrigin,attackDirection),pending={c,attackDirection,attackOrigin,attackShape,remaining:startup};if(startup>0)s.pendingChipAttack=pending;else executeChipAttack(pending);updateHud()}
A.onpointerdown=e=>{if(editMode||s.defeated||isHitStunned())return;e.preventDefault();A.classList.add('pressed');useChip()};A.onpointerup=A.onpointercancel=()=>A.classList.remove('pressed');
function clearCharge(){s.bHeld=false;s.charged=false;s.bTapAction=null;s.bHoldAction=null;s.bChargeTime=0;B.classList.remove('pressed');arrow.classList.remove('charging','ready')}
function isHitStunned(now=performance.now()){return now<s.hitStunUntil}
function getRemainingHitStunMs(now=performance.now()){return Math.max(0,s.hitStunUntil-now)}
function beginHitStun(durationMs=HIT_STUN_MS){let duration=Number(durationMs);if(!Number.isFinite(duration)||duration<=0)return false;s.hitStunUntil=performance.now()+duration;clearCharge();s.dashQueued=false;if(s.dash>0){s.dash=0;resolveDashEndCollision();s.dvx=0;s.dvy=0;player.classList.remove('dashing')}A.classList.remove('pressed');return true}
function clearHitStun(){s.hitStunUntil=0}
function setDefeated(value=true){let next=!!value;if(s.defeated===next)return s.defeated;s.defeated=next;if(next){s.pendingChipAttack=null;s.pendingBurstShots=[];clearCharge();clearHitStun();if(s.dash>0)resolveDashEndCollision();s.dash=0;s.dashQueued=false;s.dvx=0;s.dvy=0;s.ix=0;s.iy=0;player.classList.remove('dashing');joyReset();A.classList.remove('pressed');B.classList.remove('pressed');setPreviewMode('none');clearPlayerProjectiles();player.classList.add('defeated');let notice=$('defeatNotice');if(notice)notice.hidden=false;$('customGauge').disabled=true;[joy,A,B,X,Y].forEach(el=>el?.setAttribute('aria-disabled','true'))}else{player.classList.remove('defeated');let notice=$('defeatNotice');if(notice)notice.hidden=true;$('customGauge').disabled=false;[joy,A,B,X,Y].forEach(el=>el?.setAttribute('aria-disabled','false'))}updateCustomGauge();return s.defeated}
function pauseForWaveTransition(){if(s.defeated)return false;s.pendingChipAttack=null;s.pendingBurstShots=[];s.paused=true;clearCharge();if(s.dash>0)resolveDashEndCollision();s.dash=0;s.dashQueued=false;s.dvx=0;s.dvy=0;s.ix=s.iy=0;player.classList.remove('dashing');joyReset();A.classList.remove('pressed');B.classList.remove('pressed');setPreviewMode('none');clearPlayerProjectiles();return true}
function openNextWaveCustom(){if(!pauseForWaveTransition())return false;resetWave();return true}
function resumeAfterWaveTransition(){if(s.defeated)return false;if($('customModal').classList.contains('open'))return false;s.paused=false;return true}
function prepareNextWave(){if(!pauseForWaveTransition())return false;return openNextWaveCustom()}
function bDown(e){if(editMode||s.defeated||s.paused||s.dash>0||s.lock>0||isHitStunned())return;let tap=B_ATTACK.getAction('tap'),hold=B_ATTACK.getAction('hold');if(!tap&&!hold)return;e.preventDefault();s.bHeld=true;s.bAt=performance.now();s.charged=false;s.bTapAction=tap;s.bHoldAction=hold;s.bChargeTime=Number(hold?.chargeTime)||0;B.classList.add('pressed');if(hold&&s.bChargeTime>0)arrow.classList.add('charging')}
function executeBAttack(action){if(!action)return false;if(action.actionType==='PROJECTILE'){spawn(action.projectileKind||'normal',action.rangeWorld,action.speed,{x:s.dx,y:s.dy},action.damage,action.actionId);return true}console.warn('BattleNetwork: unsupported B attack actionType',action.actionType);return false}
function bUp(){if(editMode||!s.bHeld)return;if(s.dash>0){clearCharge();return}let tap=s.bTapAction,hold=s.bHoldAction,chargeTime=s.bChargeTime,charged=!!hold&&chargeTime>0&&(performance.now()-s.bAt)/1000>=chargeTime,action=charged?hold:tap;clearCharge();if(!action)return;let now=performance.now()/1000,fireInterval=Number(tap?.fireInterval)||0;if(!charged&&fireInterval>0&&now-s.lastShot<fireInterval)return;if(!charged)s.lastShot=now;executeBAttack(action)}
B.onpointerdown=bDown;B.onpointerup=bUp;B.onpointercancel=clearCharge;
function getDashMaxStocks(){const count=Math.floor(Number(playerParams().dashConsecutiveCount));return Number.isFinite(count)&&count>0?count:1}
function getDashAvailableCount(){return Math.max(0,getDashMaxStocks()-s.dashRecharge.length)}
function updateDashRecharge(dt){if(!s.dashRecharge.length)return;for(let i=s.dashRecharge.length-1;i>=0;i--){s.dashRecharge[i]-=dt;if(s.dashRecharge[i]<=0)s.dashRecharge.splice(i,1)}}
function getDashState(){const max=getDashMaxStocks(),available=Math.max(0,max-s.dashRecharge.length);return Object.freeze({max,available,recharging:s.dashRecharge.length,queued:s.dashQueued,rechargeRemaining:Object.freeze(s.dashRecharge.slice())})}
function startDash(){if(getDashAvailableCount()<=0)return false;const params=playerParams(),distance=Number(params.dashDistance),duration=Number(params.dashDuration),cooldown=Number(params.dashCooldown);if(!(distance>0)||!(duration>0)||cooldown<0)return false;let dx=s.ix,dy=s.iy,l=Math.hypot(dx,dy);if(l<DEAD){dx=s.dx;dy=s.dy;l=Math.hypot(dx,dy)||1}dx/=l;dy/=l;s.dvx=dx*distance/duration;s.dvy=dy*distance/duration;s.dash=duration;s.dashRecharge.push(cooldown);player.classList.add('dashing');return true}
function requestDash(){if(editMode||s.defeated||s.paused||s.lock>0||isHitStunned())return;if(s.dash>0){if(!s.dashQueued&&getDashAvailableCount()>0)s.dashQueued=true;return}startDash()}
X.onpointerdown=e=>{if(editMode)return;e.preventDefault();requestDash()};
function updateDirectionLockUi(){Y.classList.toggle('directionLocked',s.directionLocked);Y.setAttribute('aria-pressed',s.directionLocked?'true':'false');Y.setAttribute('aria-label',s.directionLocked?'方向固定中。タップで解除':'方向固定')}
function toggleDirectionLock(){s.directionLocked=!s.directionLocked;if(!s.directionLocked){let l=Math.hypot(s.ix,s.iy);if(l>=DEAD){s.dx=s.ix/l;s.dy=s.iy/l}}updateDirectionLockUi()}
Y.onpointerdown=e=>{if(editMode||s.defeated||s.paused||isHitStunned())return;e.preventDefault();toggleDirectionLock()};
let jid=null;function screenToWorld(x,y){let wx=(x/PX+y/PY)/2,wy=(y/PY-x/PX)/2,l=Math.hypot(wx,wy)||1;return{x:wx/l,y:wy/l}}
function joyMove(e){if(s.defeated||isHitStunned())return;let r=activeJoyRect;if(!r)return;let x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2,m=r.width*.335,d=Math.hypot(x,y),q=d>m?m/d:1,nx=x*q,ny=y*q,amt=Math.hypot(nx/m,ny/m);if(amt<DEAD)s.ix=s.iy=0;else{let w=screenToWorld(nx/m,ny/m);s.ix=w.x*amt;s.iy=w.y*amt;if(!s.directionLocked){s.dx=w.x;s.dy=w.y}}knob.style.transform=`translate(calc(-50% + ${nx}px),calc(-50% + ${ny}px))`}
function joyReset(){jid=null;activeJoyRect=null;s.ix=s.iy=0;knob.style.transform='translate(-50%,-50%)'}
joy.onpointerdown=e=>{if(editMode||s.defeated||s.paused)return;jid=e.pointerId;activeJoyRect=joy.getBoundingClientRect();joy.setPointerCapture?.(e.pointerId);joyMove(e)};joy.onpointermove=e=>{if(e.pointerId===jid)joyMove(e)};joy.onpointerup=joy.onpointercancel=joyReset;
function requestCustomOpen(e){if($('customModal').classList.contains('open'))return;if(s.defeated||!s.customReady||s.paused||editMode)return;e?.preventDefault?.();e?.stopPropagation?.();openCustom(false)}
$('customGauge').addEventListener('pointerdown',requestCustomOpen);$('customGauge').addEventListener('click',requestCustomOpen);
function openSettingsMenu(){if(editMode)return;menuOpen=true;joyReset();clearCharge();s.paused=true;$('settingsModal').classList.add('open')}
function closeSettingsMenu(resume=true){menuOpen=false;$('settingsModal').classList.remove('open');if(customHiddenForSettings){$('customModal').classList.add('open');customHiddenForSettings=false;s.paused=true;updateFooterChips();return}if(resume&&!editMode&&!$('customModal').classList.contains('open'))s.paused=false}
$('gear').addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();openSettingsMenu()});$('closeSettings').onclick=()=>closeSettingsMenu(true);$('settingsModal').addEventListener('pointerdown',e=>{if(e.target===$('settingsModal'))closeSettingsMenu(true)});
function selectTarget(key){if(selectedKey)elements[selectedKey].classList.remove('editTarget');selectedKey=key;elements[key].classList.add('editTarget');$('selectedName').textContent=names[key];$('opacitySlider').value=Math.round(controlSettings[key].opacity*100);$('opacityValue').textContent=$('opacitySlider').value+'%';$('opacityFloat').classList.add('show');updateSelectionLabel()}
function updateSelectionLabel(){if(!editMode||!selectedKey){$('selectionLabel').classList.remove('show');return}const r=elements[selectedKey].getBoundingClientRect(),b=battle.getBoundingClientRect();$('selectionLabel').textContent=names[selectedKey];$('selectionLabel').style.left=clamp(r.left-b.left,4,b.width-90)+'px';$('selectionLabel').style.top=clamp(r.top-b.top-28,4,b.height-24)+'px';$('selectionLabel').classList.add('show')}
function startEdit(){const returnToCustom=$('customModal').classList.contains('open');if(returnToCustom)$('customModal').classList.remove('open');menuOpen=false;$('settingsModal').classList.remove('open');customHiddenForSettings=returnToCustom;editMode=true;s.paused=true;battle.classList.add('editMode');$('editShade').hidden=false;$('editTopBar').classList.add('open');selectTarget(selectedKey||'left');joyReset()}
function endEdit(){editMode=false;battle.classList.remove('editMode');$('editShade').hidden=true;$('editTopBar').classList.remove('open');$('opacityFloat').classList.remove('show');$('selectionLabel').classList.remove('show');if(selectedKey)elements[selectedKey].classList.remove('editTarget');editPointers.clear();gesture=null;globalPinchPointers.clear();globalPinch=null;saveSettings();openSettingsMenu()}
$('controllerSettingsItem').onclick=startEdit;$('doneSettings').onclick=endEdit;$('resetSettings').onclick=()=>{controlSettings=cloneDefaults();applyControls();if(selectedKey)selectTarget(selectedKey);saveSettings()};$('opacitySlider').addEventListener('input',()=>{if(!selectedKey)return;controlSettings[selectedKey].opacity=Number($('opacitySlider').value)/100;$('opacityValue').textContent=$('opacitySlider').value+'%';applyControls();saveSettings()});
function pointerDistance(){const arr=[...editPointers.values()];if(arr.length<2)return 0;return Math.hypot(arr[0].x-arr[1].x,arr[0].y-arr[1].y)}
Object.entries(elements).forEach(([key,el])=>{el.addEventListener('pointerdown',e=>{if(!editMode)return;e.preventDefault();e.stopPropagation();selectTarget(key);el.setPointerCapture?.(e.pointerId);editPointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(editPointers.size===1){const v=controlSettings[key];gesture={mode:'drag',startX:e.clientX,startY:e.clientY,baseX:key==='left'?v.x:v.right,baseY:v.bottom,baseScale:v.scale,key}}else if(editPointers.size===2){gesture={mode:'pinch',startDist:pointerDistance(),baseScale:controlSettings[key].scale,key}}});el.addEventListener('pointermove',e=>{if(!editMode||!editPointers.has(e.pointerId)||!gesture)return;editPointers.set(e.pointerId,{x:e.clientX,y:e.clientY});const v=controlSettings[gesture.key];if(gesture.mode==='drag'&&editPointers.size===1){const dx=e.clientX-gesture.startX,dy=e.clientY-gesture.startY;if(gesture.key==='left'){v.x=clamp(gesture.baseX+dx,-40,battle.clientWidth-60);v.bottom=clamp(gesture.baseY-dy,-40,battle.clientHeight-60)}else{v.right=clamp(gesture.baseX-dx,-40,battle.clientWidth-60);v.bottom=clamp(gesture.baseY-dy,-40,battle.clientHeight-60)}applyControls()}else if(editPointers.size>=2){const d=pointerDistance();if(!gesture.startDist)gesture.startDist=d;v.scale=clamp(gesture.baseScale*(d/gesture.startDist),.55,1.6);applyControls()}});const end=e=>{if(!editMode)return;editPointers.delete(e.pointerId);gesture=null;saveSettings()};el.addEventListener('pointerup',end);el.addEventListener('pointercancel',end);el.addEventListener('lostpointercapture',end)});
const globalPinchPointers=new Map();let globalPinch=null;function globalPinchDistance(){const p=[...globalPinchPointers.values()];return p.length<2?0:Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y)}function isEditUiTarget(target){return !!target.closest('.editTopBar,.opacityFloat')}
battle.addEventListener('pointerdown',e=>{if(!editMode||!selectedKey||isEditUiTarget(e.target)||e.target.closest('.joy,.act'))return;globalPinchPointers.set(e.pointerId,{x:e.clientX,y:e.clientY});battle.setPointerCapture?.(e.pointerId);if(globalPinchPointers.size===2)globalPinch={startDist:globalPinchDistance(),baseScale:controlSettings[selectedKey].scale,key:selectedKey}});battle.addEventListener('pointermove',e=>{if(!editMode||!globalPinchPointers.has(e.pointerId))return;globalPinchPointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(globalPinchPointers.size>=2&&globalPinch){const d=globalPinchDistance();if(globalPinch.startDist>0){controlSettings[globalPinch.key].scale=clamp(globalPinch.baseScale*(d/globalPinch.startDist),.55,1.6);applyControls()}}});function endGlobalPinch(e){if(!globalPinchPointers.has(e.pointerId))return;globalPinchPointers.delete(e.pointerId);if(globalPinchPointers.size<2){globalPinch=null;saveSettings()}}battle.addEventListener('pointerup',endGlobalPinch);battle.addEventListener('pointercancel',endGlobalPinch);battle.addEventListener('lostpointercapture',endGlobalPinch);
function loop(t){let elapsed=Math.max(0,(t-s.last)/1000),dt=Math.min(elapsed,.05);s.last=t;if(!s.paused&&!editMode&&!menuOpen&&!s.defeated){if(s.lock>0)s.lock=Math.max(0,s.lock-elapsed);if(s.pendingChipAttack){s.pendingChipAttack.remaining-=elapsed;if(s.pendingChipAttack.remaining<=0){let pending=s.pendingChipAttack;s.pendingChipAttack=null;executeChipAttack(pending)}}if(s.pendingBurstShots.length){for(const shot of s.pendingBurstShots)shot.remaining-=elapsed;const ready=s.pendingBurstShots.filter(shot=>shot.remaining<=0);s.pendingBurstShots=s.pendingBurstShots.filter(shot=>shot.remaining>0);ready.forEach(firePendingBurstShot)}updateDashRecharge(elapsed);if(!s.customReady){s.custom+=elapsed;if(s.custom>=CUSTOM_TIME){s.custom=CUSTOM_TIME;s.customReady=true}updateCustomGauge()}if(s.bHeld&&!s.charged&&s.bHoldAction&&s.bChargeTime>0&&(t-s.bAt)/1000>=s.bChargeTime){s.charged=true;arrow.classList.remove('charging');arrow.classList.add('ready')}if(s.dash>0){let k=Math.min(dt,s.dash);if(s.dvx)tryPlayerDashPosition(s.x+s.dvx*k,s.y);if(s.dvy)tryPlayerDashPosition(s.x,s.y+s.dvy*k);s.dash-=k;if(s.dash<=0){s.dash=0;if(s.dashQueued&&getDashAvailableCount()>0){s.dashQueued=false;startDash()}else{s.dashQueued=false;resolveDashEndCollision();player.classList.remove('dashing')}}}else if(s.lock<=0&&!isHitStunned(t)){const speed=playerParams().moveSpeed;movePlayerWithCollision(s.ix*speed*dt,s.iy*speed*dt)}}s.x=clamp(s.x,0,WORLD);s.y=clamp(s.y,0,WORLD);updatePlayerTile();let pp=proj(s.x,s.y),ang=angle(s.dx,s.dy);player.style.transform=`translate(${pp.x-PLAYER_VISUAL.width/2}px,${pp.y-PLAYER_VISUAL.height}px)`;arrow.style.transform=`translate(${pp.x}px,${pp.y-36}px) rotate(${ang}deg)`;renderPreview();for(let i=bullets.length-1;i>=0;i--){let b=bullets[i];b.x+=b.dx*b.speed*dt;b.y+=b.dy*b.speed*dt;b.dist+=b.speed*dt;let p=proj(b.x,b.y),a=angle(b.dx,b.dy);if(b.layer==='buster')B_PROJECTILE.update(b.el,p.x,p.y,a);else{b.el.style.transform=`translate(${p.x-9}px,${p.y-34}px) rotate(${a}deg)`;P_SHADOW.update(b.el,p.x,p.y)}if(Number.isFinite(b.damage)&&b.damage>0&&hitBusterEnemy(b)){if(b.layer==='buster')B_PROJECTILE.remove(b.el);else{P_SHADOW.detach(b.el);b.el.remove()}bullets.splice(i,1);continue}if(b.dist>=b.range){if(b.layer==='buster')B_PROJECTILE.remove(b.el);else{P_SHADOW.detach(b.el);b.el.remove()}bullets.splice(i,1)}}if(!window.BattleNetworkCameraZoomSettings){let c=camera(),f=1-Math.pow(1-FOLLOW,dt*60);s.cx=lerp(s.cx,c.x,f);s.cy=lerp(s.cy,c.y,f);scene.style.transform=`scale(${CAMERA_ZOOM}) translate(${-s.cx}px,${-s.cy}px)`;}const dashState=getDashState();X.classList.toggle('cool',dashState.available<=0&&!dashState.queued);X.dataset.dashStock=`${dashState.available}/${dashState.max}`;X.dataset.dashQueued=dashState.queued?'true':'false';requestAnimationFrame(loop)}
function getParameters(){return playerParams()}
function setParameterAdditive(sourceId,values){return PARAMS.setAdditive('player',sourceId,values)}
function removeParameterAdditive(sourceId){return PARAMS.removeAdditive('player',sourceId)}
window.BattleNetworkPlayer=Object.freeze({HIT_STUN_MS,getParameters,setParameterAdditive,removeParameterAdditive,getDashState,getPosition:()=>Object.freeze({x:s.x,y:s.y}),getVisual:()=>PLAYER_VISUAL,getHitBox:()=>PLAYER_HITBOX,getBounds:getPlayerBounds,containsPoint:playerContainsPoint,isDirectionLocked:()=>s.directionLocked,getFacing:()=>Object.freeze({x:s.dx,y:s.dy}),isDashing:()=>s.dash>0,beginHitStun,isHitStunned,getRemainingHitStunMs,clearHitStun,setDefeated,isDefeated:()=>s.defeated,pauseForWaveTransition,openNextWaveCustom,resumeAfterWaveTransition,prepareNextWave});
window.BattleNetworkCombatRange=Object.freeze({getLastAttackRange:()=>s.lastAttackRange,getLastAttackContext:()=>s.lastAttackContext,containsPoint:(x,y)=>RANGE.containsPoint(s.lastAttackRange,x,y),getTilesByCenter:()=>RANGE.getTilesByCenter(s.lastAttackRange),getBombRangeConfig:()=>({radiusTiles:CHIP.BOMB.radiusTiles,throwDistanceTiles:CHIP.BOMB.throwDistanceTiles})});
window.addEventListener('resize',()=>{refreshBattleSize();activeJoyRect=null;updateSelectionLabel()});refreshBattleSize();applyControls();updateDirectionLockUi();updatePlayerTile();PLAYER_HEALTH.subscribe(health=>setDefeated(health.isDefeated));resetWave();let c=camera();s.cx=c.x;s.cy=c.y;requestAnimationFrame(loop)
})();
