(()=>{
const $=id=>document.getElementById(id),battle=$('battle'),scene=$('scene'),player=$('player'),arrow=$('arrow'),joy=$('joy'),knob=$('knob'),A=$('A'),B=$('B'),X=$('X'),Y=$('Y');
const FIELD=window.BattleNetworkField,RANGE=window.BattleNetworkRangeGeometry,RANGE_PREVIEW=window.BattleNetworkRangePreview,BOMB_PREVIEW=window.BattleNetworkBombPreview;
if(!FIELD)throw new Error('BattleNetwork: logical field grid is not loaded.');
if(!RANGE||!RANGE_PREVIEW||!BOMB_PREVIEW)throw new Error('BattleNetwork: combat range system is not loaded.');
const WORLD=FIELD.WORLD_SIZE,PX=.72,PY=.36,SW=WORLD*PX*2,SH=WORLD*PY*2,SPEED=260,DEAD=.12,FOLLOW=.14,CAMERA_ZOOM=.62,DASH_DIST=180,DASH_TIME=.13,DASH_CD=.65,BUSTER_RANGE=750,BUSTER_SPEED=1050,CHARGE=.85,FIRE=.67,CUSTOM_TIME=10,LONG_PRESS_MS=520;
const {CHIP,ATTR_IMAGE,ATTR_LABEL}=window.BattleNetworkMaster.createGameCompatibilityData();
const folder=[['CANNON','A'],['SWORD','S'],['WIDE','S'],['BOMB','B'],['RECOVER','A'],['CANNON','B'],['SWORD','E'],['WIDE','E'],['BOMB','L'],['RECOVER','L'],['CANNON','C'],['SWORD','S'],['WIDE','S'],['BOMB','*'],['RECOVER','A'],['CANNON','*'],['SWORD','E'],['WIDE','E'],['BOMB','B'],['RECOVER','L'],['CANNON','A'],['SWORD','S'],['WIDE','S'],['BOMB','L'],['RECOVER','A'],['CANNON','B'],['SWORD','E'],['WIDE','E'],['BOMB','*'],['RECOVER','L']];
let uid=0;const cards=folder.map(([type,code])=>({id:uid++,type,code}));
const s={x:WORLD/2,y:WORLD/2,ix:0,iy:0,dx:1,dy:0,cx:0,cy:0,tileRow:null,tileCol:null,currentTile:null,currentTerrain:null,lastAttackRange:null,last:performance.now(),dash:0,dashCd:0,dvx:0,dvy:0,bHeld:false,bAt:0,charged:false,lastShot:-1e9,lock:0,paused:true,custom:0,customReady:false,queue:[],draw:[],discard:new Set(),hand:[],selected:[]},bullets=[];
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t;
let editMode=false,menuOpen=false,customHiddenForSettings=false,previewMode='none';
let battleWidth=0,battleHeight=0,activeJoyRect=null;
const defaults={left:{x:18,bottom:16,scale:1,opacity:1},A:{right:82,bottom:16,scale:1,opacity:1},B:{right:8,bottom:88,scale:1,opacity:1},X:{right:156,bottom:88,scale:1,opacity:1},Y:{right:82,bottom:160,scale:1,opacity:1}};
let controlSettings=loadSettings(),selectedKey=null,editPointers=new Map(),gesture=null;
const elements={left:joy,A,B,X,Y},names={left:'左スティック',A:'Aボタン',B:'Bボタン',X:'Xボタン',Y:'Yボタン'};
function cloneDefaults(){return JSON.parse(JSON.stringify(defaults))}
function loadSettings(){try{const v=JSON.parse(localStorage.getItem('battleNetworkControlsV3'));return v&&v.left&&v.A&&v.B&&v.X&&v.Y?v:cloneDefaults()}catch{return cloneDefaults()}}
function saveSettings(){localStorage.setItem('battleNetworkControlsV3',JSON.stringify(controlSettings))}
function refreshBattleSize(){battleWidth=battle.clientWidth;battleHeight=battle.clientHeight}
function applyControls(){const l=controlSettings.left;joy.style.left=l.x+'px';joy.style.bottom=l.bottom+'px';joy.style.transform=`scale(${l.scale})`;joy.style.opacity=l.opacity;['A','B','X','Y'].forEach(k=>{const el=elements[k],v=controlSettings[k];el.style.right=v.right+'px';el.style.bottom=v.bottom+'px';el.style.transform=`scale(${v.scale})`;el.style.opacity=v.opacity});activeJoyRect=null;updateSelectionLabel()}
function proj(x,y){return{x:(x-y)*PX+SW/2,y:(x+y)*PY}}
function angle(dx,dy){return Math.atan2((dx+dy)*PY,(dx-dy)*PX)*180/Math.PI}
function unit(dx,dy){let x=(dx-dy)*PX,y=(dx+dy)*PY,l=Math.hypot(x,y)||1;return{x:x/l,y:y/l}}
function camera(){let p=proj(s.x,s.y),vw=battleWidth/CAMERA_ZOOM,vh=battleHeight/CAMERA_ZOOM;return{x:clamp(p.x-vw/2,0,SW-vw),y:clamp(p.y-vh*.58,0,SH-vh)}}
function updatePlayerTile(){let tile=FIELD.getTileAtWorld(s.x,s.y);if(!tile)return;let changed=s.tileRow!==tile.row||s.tileCol!==tile.col||s.currentTerrain!==tile.currentTerrain;s.currentTile=tile;if(!changed)return;s.tileRow=tile.row;s.tileCol=tile.col;s.currentTerrain=tile.currentTerrain;player.dataset.tileRow=String(tile.row);player.dataset.tileCol=String(tile.col);player.dataset.terrain=tile.currentTerrain}
function buildChipRange(ch,origin={x:s.x,y:s.y},direction={x:s.dx,y:s.dy}){return RANGE.createFromChip(ch,{origin,direction})}
function buildBombRange(ch,origin={x:s.x,y:s.y},direction={x:s.dx,y:s.dy}){let dir=RANGE.normalizeDirection(direction),throwTiles=Number(ch?.throwDistanceTiles),distance=FIELD.toWorldDistance(Number.isFinite(throwTiles)?throwTiles:3),center={x:origin.x+dir.x*distance,y:origin.y+dir.y*distance};return RANGE.createCircle(center,ch?.radiusTiles??.75)}
function card(id){return cards.find(c=>c.id===id)}
function shuffle(a){for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function resetWave(){s.draw=shuffle(cards.map(c=>c.id));s.discard.clear();s.queue=[];s.custom=0;s.customReady=false;s.hand=[];openCustom(true)}
function nextHand(){s.hand=s.draw.slice(0,5);s.selected=[];renderCustom()}
function openCustom(initial=false){s.paused=true;joyReset();clearCharge();$('customModal').classList.add('open');if(initial||!s.hand.length)nextHand();else renderCustom();updateFooterChips()}
function validSelection(ids){if(ids.length<=1)return true;let cs=ids.map(card);if(cs.every(c=>c.type===cs[0].type))return true;return new Set(cs.filter(c=>c.code!=='*').map(c=>c.code)).size<=1}
function canAdd(id){return s.selected.includes(id)||validSelection([...s.selected,id])}
function attrHtml(type){let attr=CHIP[type].attr,src=ATTR_IMAGE[attr]||ATTR_IMAGE.normal,label=ATTR_LABEL[attr]||ATTR_LABEL.normal;return `<img class="attrIcon" src="${src}" alt="${label}" draggable="false">`}
function chipArtHtml(type){let src=CHIP[type].image;return src?`<img src="${src}" alt="${CHIP[type].name}" draggable="false">`:''}
function footerIds(){return $('customModal').classList.contains('open')&&s.selected.length?s.selected:s.queue}
function updateFooterChips(){$('chipNow').textContent='チップ';$('queue').innerHTML='';let ids=footerIds();if(!ids.length){let d=document.createElement('span');d.className='q empty';d.textContent='--';$('queue').appendChild(d);return}ids.forEach(id=>{let c=card(id),d=document.createElement('span');d.className='q';d.textContent=CHIP[c.type].name;$('queue').appendChild(d)})}
function showChipDetail(id){let c=card(id),ch=CHIP[c.type],attr=ATTR_LABEL[ch.attr]||ATTR_LABEL.normal;$('detailName').textContent=ch.name;$('detailArt').innerHTML=chipArtHtml(c.type);$('detailAttrIcon').innerHTML=attrHtml(c.type);$('detailAttr').textContent=attr;$('detailDesc').textContent=ch.detail;$('detailPower').textContent=ch.type==='recover'?`回復量：${ch.heal}`:`攻撃力：${ch.power}`;$('detailRangeText').textContent=ch.rangeText;$('detailRange').className='rangeViz '+ch.viz;$('chipDetailModal').classList.add('open');$('chipDetailModal').querySelector('.chipDetail').scrollTop=0}
function closeChipDetail(){$('chipDetailModal').classList.remove('open')}
$('detailClose').onclick=closeChipDetail;$('chipDetailModal').addEventListener('pointerdown',e=>{if(e.target===$('chipDetailModal'))closeChipDetail()});
function bindChipCard(b,id,ok){let timer=null,startX=0,startY=0,longPressed=false;const clear=()=>{if(timer){clearTimeout(timer);timer=null}};b.addEventListener('pointerdown',e=>{startX=e.clientX;startY=e.clientY;longPressed=false;clear();timer=setTimeout(()=>{timer=null;longPressed=true;showChipDetail(id)},LONG_PRESS_MS)});b.addEventListener('pointermove',e=>{if(Math.hypot(e.clientX-startX,e.clientY-startY)>12)clear()});b.addEventListener('pointerup',clear);b.addEventListener('pointercancel',clear);b.addEventListener('lostpointercapture',clear);b.addEventListener('click',e=>{if(longPressed){longPressed=false;e.preventDefault();e.stopPropagation();return}if(!ok)return;let i=s.selected.indexOf(id);i>=0?s.selected.splice(i,1):s.selected.push(id);renderCustom()})}
function renderCustom(){$('folderInfo').textContent=`フォルダ ${s.draw.length}`;$('hand').innerHTML='';for(let slot=0;slot<10;slot++){let id=s.hand[slot];if(id===undefined){let e=document.createElement('div');e.className='chipCard empty';e.innerHTML=`<span class="slotNo">${slot+1}</span><span class="chipName">---</span><span class="chipArt"></span><span class="chipMeta"><span class="chipCode">-</span><span class="chipAttr"></span><span class="chipValue">--</span></span>`;$('hand').appendChild(e);continue}let c=card(id),b=document.createElement('button'),ok=canAdd(id);b.className='chipCard'+(s.selected.includes(id)?' sel':'')+(!ok?' blocked':'');b.innerHTML=`<span class="slotNo">${slot+1}</span><span class="chipName">${CHIP[c.type].name}</span><span class="chipArt">${chipArtHtml(c.type)}</span><span class="chipMeta"><span class="chipCode">${c.code}</span><span class="chipAttr">${attrHtml(c.type)}</span><span class="chipValue">--</span></span>`;bindChipCard(b,id,ok);$('hand').appendChild(b)}updateFooterChips()}
$('send').onclick=()=>{if(s.selected.length){s.queue.forEach(id=>s.discard.add(id));let ss=new Set(s.selected);s.hand.forEach(id=>{let p=s.draw.indexOf(id);if(p>=0)s.draw.splice(p,1);if(!ss.has(id))s.discard.add(id)});s.queue=s.selected.slice()}else if(!s.queue.length)return;s.hand=[];s.selected=[];s.custom=0;s.customReady=false;$('customModal').classList.remove('open');s.paused=false;updateHud()};
function setPreviewMode(mode){if(previewMode===mode)return;previewMode=mode;if(mode==='none'){RANGE_PREVIEW.hide();BOMB_PREVIEW.hide()}else if(mode==='range'){BOMB_PREVIEW.hide()}}
function renderPreview(){if(!s.queue.length){setPreviewMode('none');return}let ch=CHIP[card(s.queue[0]).type];if(ch.type==='recover'){setPreviewMode('none');return}if(ch.type==='bomb'){let shape=buildBombRange(ch);setPreviewMode('bomb');RANGE_PREVIEW.render(shape);BOMB_PREVIEW.render({x:s.x,y:s.y},shape.center);return}let shape=buildChipRange(ch);if(shape&&(shape.rangeTypeId==='LINE'||shape.rangeTypeId==='RECT'||shape.rangeTypeId==='CIRCLE')){setPreviewMode('range');RANGE_PREVIEW.render(shape);return}setPreviewMode('none')}
function updateCustomGauge(){let pc=Math.min(s.custom,CUSTOM_TIME)/CUSTOM_TIME*100;$('customFill').style.width=pc+'%';$('customGauge').classList.toggle('ready',s.customReady);$('customGauge').setAttribute('aria-disabled',s.customReady?'false':'true')}
function updateHud(){updateFooterChips();updateCustomGauge();renderPreview()}
function spawn(kind,range=BUSTER_RANGE,speed=BUSTER_SPEED,direction={x:s.dx,y:s.dy}){let d={x:direction.x,y:direction.y},l=Math.hypot(d.x,d.y)||1;d.x/=l;d.y/=l;let b={x:s.x,y:s.y,dx:d.x,dy:d.y,dist:0,range,speed,kind,el:document.createElement('div')};b.el.className='bullet '+kind;scene.appendChild(b.el);bullets.push(b)}
function effect(cls,x,y,w,h){let e=document.createElement('div');e.className=cls;e.style.cssText=`width:${w}px;height:${h}px;left:${x-w/2}px;top:${y-h/2}px`;scene.appendChild(e);setTimeout(()=>e.remove(),700)}
function useChip(){if(s.paused||s.dash>0||s.lock>0||!s.queue.length||editMode)return;let id=s.queue.shift(),c=CHIP[card(id).type];s.discard.add(id);s.lock=c.lock||.25;let attackDirection=RANGE.normalizeDirection({x:s.dx,y:s.dy}),attackOrigin={x:s.x,y:s.y},attackShape=c.type==='bomb'?buildBombRange(c,attackOrigin,attackDirection):buildChipRange(c,attackOrigin,attackDirection);s.lastAttackRange=attackShape;let p=proj(s.x,s.y),u=unit(attackDirection.x,attackDirection.y);if(c.type==='cannon')spawn('cannon',attackShape?.lengthWorld??c.range,c.projectileSpeed||900,attackDirection);else if(c.type==='sword'||c.type==='wide'){let range=attackShape?.lengthWorld??c.range,width=attackShape?.widthWorld??c.width;effect('slash',p.x+u.x*range*PX*.45,p.y-30+u.y*range*PX*.45,range*PX,width*PY)}else if(c.type==='bomb'){let center=attackShape?.center||attackOrigin,target=proj(center.x,center.y),radius=attackShape?.radiusWorld??c.radius;setTimeout(()=>effect('boom',target.x,target.y-30,radius*PX*2,radius*PX*2),(c.explosionDelay??.28)*1000)}else effect('healPulse',p.x,p.y-36,86,86);updateHud()}
A.onpointerdown=e=>{if(editMode)return;e.preventDefault();A.classList.add('pressed');useChip()};A.onpointerup=A.onpointercancel=()=>A.classList.remove('pressed');
function clearCharge(){s.bHeld=false;s.charged=false;B.classList.remove('pressed');arrow.classList.remove('charging','ready')}
function bDown(e){if(editMode||s.paused||s.dash>0||s.lock>0)return;e.preventDefault();s.bHeld=true;s.bAt=performance.now();s.charged=false;B.classList.add('pressed');arrow.classList.add('charging')}
function bUp(){if(editMode||!s.bHeld)return;if(s.dash>0){clearCharge();return}let charged=(performance.now()-s.bAt)/1000>=CHARGE;clearCharge();let now=performance.now()/1000;if(!charged&&now-s.lastShot<FIRE)return;if(!charged)s.lastShot=now;spawn(charged?'charged':'normal',BUSTER_RANGE,charged?820:BUSTER_SPEED)}
B.onpointerdown=bDown;B.onpointerup=bUp;B.onpointercancel=clearCharge;
function dash(){if(editMode||s.paused||s.lock>0||s.dashCd>0)return;let dx=s.ix,dy=s.iy,l=Math.hypot(dx,dy);if(l<DEAD){dx=s.dx;dy=s.dy;l=Math.hypot(dx,dy)||1}dx/=l;dy/=l;s.dvx=dx*DASH_DIST/DASH_TIME;s.dvy=dy*DASH_DIST/DASH_TIME;s.dash=DASH_TIME;s.dashCd=DASH_CD;player.classList.add('dashing')}
X.onpointerdown=e=>{if(editMode)return;e.preventDefault();dash()};
let jid=null;function screenToWorld(x,y){let wx=(x/PX+y/PY)/2,wy=(y/PY-x/PX)/2,l=Math.hypot(wx,wy)||1;return{x:wx/l,y:wy/l}}
function joyMove(e){let r=activeJoyRect;if(!r)return;let x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2,m=r.width*.335,d=Math.hypot(x,y),q=d>m?m/d:1,nx=x*q,ny=y*q,amt=Math.hypot(nx/m,ny/m);if(amt<DEAD)s.ix=s.iy=0;else{let w=screenToWorld(nx/m,ny/m);s.ix=w.x*amt;s.iy=w.y*amt;s.dx=w.x;s.dy=w.y}knob.style.transform=`translate(calc(-50% + ${nx}px),calc(-50% + ${ny}px))`}
function joyReset(){jid=null;activeJoyRect=null;s.ix=s.iy=0;knob.style.transform='translate(-50%,-50%)'}
joy.onpointerdown=e=>{if(editMode||s.paused)return;jid=e.pointerId;activeJoyRect=joy.getBoundingClientRect();joy.setPointerCapture?.(e.pointerId);joyMove(e)};joy.onpointermove=e=>{if(e.pointerId===jid)joyMove(e)};joy.onpointerup=joy.onpointercancel=joyReset;
function requestCustomOpen(e){if($('customModal').classList.contains('open'))return;if(!s.customReady||s.paused||editMode)return;e?.preventDefault?.();e?.stopPropagation?.();openCustom(false)}
$('customGauge').addEventListener('pointerdown',requestCustomOpen);$('customGauge').addEventListener('click',requestCustomOpen);
function openSettingsMenu(){if(editMode)return;menuOpen=true;joyReset();clearCharge();s.paused=true;$('settingsModal').classList.add('open')}
function closeSettingsMenu(resume=true){menuOpen=false;$('settingsModal').classList.remove('open');if(customHiddenForSettings){$('customModal').classList.add('open');customHiddenForSettings=false;s.paused=true;updateFooterChips();return}if(resume&&!editMode&&!$('customModal').classList.contains('open'))s.paused=false}
$('gear').addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();openSettingsMenu()});$('closeSettings').onclick=()=>closeSettingsMenu(true);$('settingsModal').addEventListener('pointerdown',e=>{if(e.target===$('settingsModal'))closeSettingsMenu(true)});
function selectTarget(key){if(selectedKey)elements[selectedKey].classList.remove('editTarget');selectedKey=key;elements[key].classList.add('editTarget');$('selectedName').textContent=names[key];$('opacitySlider').value=Math.round(controlSettings[key].opacity*100);$('opacityValue').textContent=$('opacitySlider').value+'%';$('opacityFloat').classList.add('show');updateSelectionLabel()}
function updateSelectionLabel(){if(!editMode||!selectedKey){$('selectionLabel').classList.remove('show');return}const r=elements[selectedKey].getBoundingClientRect(),b=battle.getBoundingClientRect();$('selectionLabel').textContent=names[selectedKey];$('selectionLabel').style.left=clamp(r.left-b.left,4,b.width-90)+'px';$('selectionLabel').style.top=clamp(r.top-b.top-28,4,b.height-24)+'px';$('selectionLabel').classList.add('show')}
function startEdit(){const returnToCustom=$('customModal').classList.contains('open');if(returnToCustom)$('customModal').classList.remove('open');menuOpen=false;$('settingsModal').classList.remove('open');customHiddenForSettings=returnToCustom;editMode=true;s.paused=true;battle.classList.add('editMode');$('editShade').hidden=false;$('editTopBar').classList.add('open');selectTarget(selectedKey||'left');joyReset()}
function endEdit(){editMode=false;battle.classList.remove('editMode');$('editShade').hidden=true;$('editTopBar').classList.remove('open');$('opacityFloat').classList.remove('show');$('selectionLabel').classList.remove('show');if(selectedKey)elements[selectedKey].classList.remove('editTarget');editPointers.clear();gesture=null;globalPinchPointers.clear();globalPinch=null;saveSettings();openSettingsMenu()}
$('controllerSettingsItem').onclick=startEdit;$('doneSettings').onclick=endEdit;$('resetSettings').onclick=()=>{controlSettings=cloneDefaults();applyControls();if(selectedKey)selectTarget(selectedKey);saveSettings()};$('opacitySlider').addEventListener('input',()=>{if(!selectedKey)return;controlSettings[selectedKey].opacity=Number($('opacitySlider').value)/100;$('opacityValue').textContent=$('opacitySlider').value+'%';applyControls();saveSettings()});
function pointerDistance(){const arr=[...editPointers.values()];if(arr.length<2)return 0;return Math.hypot(arr[0].x-arr[1].x,arr[0].y-arr[1].y)}
Object.entries(elements).forEach(([key,el])=>{el.addEventListener('pointerdown',e=>{if(!editMode)return;e.preventDefault();e.stopPropagation();selectTarget(key);el.setPointerCapture?.(e.pointerId);editPointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(editPointers.size===1){const v=controlSettings[key];gesture={mode:'drag',startX:e.clientX,startY:e.clientY,baseX:key==='left'?v.x:v.right,baseY:v.bottom,baseScale:v.scale,key}}else if(editPointers.size===2){gesture={mode:'pinch',startDist:pointerDistance(),baseScale:controlSettings[key].scale,key}}});el.addEventListener('pointermove',e=>{if(!editMode||!editPointers.has(e.pointerId)||!gesture)return;editPointers.set(e.pointerId,{x:e.clientX,y:e.clientY});const v=controlSettings[gesture.key];if(gesture.mode==='drag'&&editPointers.size===1){const dx=e.clientX-gesture.startX,dy=e.clientY-gesture.startY;if(gesture.key==='left'){v.x=clamp(gesture.baseX+dx,-40,battle.clientWidth-60);v.bottom=clamp(gesture.baseY-dy,-40,battle.clientHeight-60)}else{v.right=clamp(gesture.baseX-dx,-40,battle.clientWidth-60);v.bottom=clamp(gesture.baseY-dy,-40,battle.clientHeight-60)}applyControls()}else if(editPointers.size>=2){const d=pointerDistance();if(!gesture.startDist)gesture.startDist=d;v.scale=clamp(gesture.baseScale*(d/gesture.startDist),.55,1.6);applyControls()}});const end=e=>{if(!editMode)return;editPointers.delete(e.pointerId);gesture=null;saveSettings()};el.addEventListener('pointerup',end);el.addEventListener('pointercancel',end);el.addEventListener('lostpointercapture',end)});
const globalPinchPointers=new Map();let globalPinch=null;function globalPinchDistance(){const p=[...globalPinchPointers.values()];return p.length<2?0:Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y)}function isEditUiTarget(target){return !!target.closest('.editTopBar,.opacityFloat')}
battle.addEventListener('pointerdown',e=>{if(!editMode||!selectedKey||isEditUiTarget(e.target)||e.target.closest('.joy,.act'))return;globalPinchPointers.set(e.pointerId,{x:e.clientX,y:e.clientY});battle.setPointerCapture?.(e.pointerId);if(globalPinchPointers.size===2)globalPinch={startDist:globalPinchDistance(),baseScale:controlSettings[selectedKey].scale,key:selectedKey}});battle.addEventListener('pointermove',e=>{if(!editMode||!globalPinchPointers.has(e.pointerId))return;globalPinchPointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(globalPinchPointers.size>=2&&globalPinch){const d=globalPinchDistance();if(globalPinch.startDist>0){controlSettings[globalPinch.key].scale=clamp(globalPinch.baseScale*(d/globalPinch.startDist),.55,1.6);applyControls()}}});function endGlobalPinch(e){if(!globalPinchPointers.has(e.pointerId))return;globalPinchPointers.delete(e.pointerId);if(globalPinchPointers.size<2){globalPinch=null;saveSettings()}}battle.addEventListener('pointerup',endGlobalPinch);battle.addEventListener('pointercancel',endGlobalPinch);battle.addEventListener('lostpointercapture',endGlobalPinch);
function loop(t){let dt=Math.min((t-s.last)/1000,.05);s.last=t;if(!s.paused&&!editMode&&!menuOpen){if(s.lock>0)s.lock=Math.max(0,s.lock-dt);if(s.dashCd>0)s.dashCd=Math.max(0,s.dashCd-dt);if(!s.customReady){s.custom+=dt;if(s.custom>=CUSTOM_TIME){s.custom=CUSTOM_TIME;s.customReady=true}updateCustomGauge()}if(s.bHeld&&!s.charged&&(t-s.bAt)/1000>=CHARGE){s.charged=true;arrow.classList.remove('charging');arrow.classList.add('ready')}if(s.dash>0){let k=Math.min(dt,s.dash);s.x+=s.dvx*k;s.y+=s.dvy*k;s.dash-=k;if(s.dash<=0)player.classList.remove('dashing')}else if(s.lock<=0){s.x+=s.ix*SPEED*dt;s.y+=s.iy*SPEED*dt}}s.x=clamp(s.x,0,WORLD);s.y=clamp(s.y,0,WORLD);updatePlayerTile();let pp=proj(s.x,s.y),ang=angle(s.dx,s.dy);player.style.transform=`translate(${pp.x-22}px,${pp.y-56}px)`;arrow.style.transform=`translate(${pp.x}px,${pp.y-30}px) rotate(${ang}deg)`;renderPreview();for(let i=bullets.length-1;i>=0;i--){let b=bullets[i];b.x+=b.dx*b.speed*dt;b.y+=b.dy*b.speed*dt;b.dist+=b.speed*dt;let p=proj(b.x,b.y),a=angle(b.dx,b.dy);b.el.style.transform=`translate(${p.x-9}px,${p.y-34}px) rotate(${a}deg)`;if(b.dist>=b.range){b.el.remove();bullets.splice(i,1)}}let c=camera(),f=1-Math.pow(1-FOLLOW,dt*60);s.cx=lerp(s.cx,c.x,f);s.cy=lerp(s.cy,c.y,f);scene.style.transform=`scale(${CAMERA_ZOOM}) translate(${-s.cx}px,${-s.cy}px)`;X.classList.toggle('cool',s.dashCd>0);requestAnimationFrame(loop)}
window.BattleNetworkCombatRange=Object.freeze({getLastAttackRange:()=>s.lastAttackRange,containsPoint:(x,y)=>RANGE.containsPoint(s.lastAttackRange,x,y),getTilesByCenter:()=>RANGE.getTilesByCenter(s.lastAttackRange),getBombRangeConfig:()=>({radiusTiles:CHIP.BOMB.radiusTiles,throwDistanceTiles:CHIP.BOMB.throwDistanceTiles})});
window.addEventListener('resize',()=>{refreshBattleSize();activeJoyRect=null;updateSelectionLabel()});refreshBattleSize();applyControls();updatePlayerTile();resetWave();let c=camera();s.cx=c.x;s.cy=c.y;requestAnimationFrame(loop)
})();