from pathlib import Path


def replace_once(path, old, new):
    p = Path(path)
    text = p.read_text(encoding='utf-8')
    if old not in text:
        raise SystemExit(f'expected text not found in {path}: {old[:120]}')
    p.write_text(text.replace(old, new, 1), encoding='utf-8')

# game.js: connect Recovery10 to player health while preserving the existing chip-consumption flow.
replace_once(
    'js/game.js',
    "B_PROJECTILE=window.BattleNetworkBusterProjectile,ENEMY=window.BattleNetworkEnemy;",
    "B_PROJECTILE=window.BattleNetworkBusterProjectile,ENEMY=window.BattleNetworkEnemy,PLAYER_HEALTH=window.BattleNetworkPlayerHealth;"
)
replace_once(
    'js/game.js',
    "if(!ENEMY)throw new Error('BattleNetwork: enemy foundation is not loaded.');",
    "if(!ENEMY)throw new Error('BattleNetwork: enemy foundation is not loaded.');\nif(!PLAYER_HEALTH)throw new Error('BattleNetwork: player health is not loaded.');"
)
replace_once(
    'js/game.js',
    "}else effect('healPulse',p.x,p.y-36,86,86);updateHud()}",
    "}else if(c.type==='recover'){PLAYER_HEALTH.applyHealing(c.heal);effect('healPulse',p.x,p.y-36,86,86)}updateHud()}"
)

# Browser cache-busting.
replace_once('index.html', './js/combat/player-health.js?v=86', './js/combat/player-health.js?v=90')
replace_once('index.html', './js/game.js?v=89', './js/game.js?v=90')
replace_once('sw.js', "battlenetwork-runtime-v89", "battlenetwork-runtime-v90")

# Development status.
status = Path('DEVELOPMENT_STATUS.md')
text = status.read_text(encoding='utf-8')
anchor = "v89でキャノンのBehaviorを正式設計どおり非貫通へ修正した。従来は `CANNON_SHOT` がLINE Range内の全敵へ到達時間ごとにダメージを予約していたため、射線上に複数敵がいる場合に後方の敵までダメージが入っていた。`getFirstCannonHit()` で発射方向上の最前面HitBoxだけを取得し、ダメージ対象をその1体に限定する。同時に `game.js` のキャノン弾の飛翔距離も最初の敵までへ短縮し、最初の敵へ到達した時点で弾DOMを消す。キャノンのRange `LINE(5×0.75)`、威力、弾速、表示サイズ、床影は変更しない。実機確認で、キャノン弾が最初の敵で停止し、後方へ貫通しないことを確認済み。"
addition = anchor + "\n\nv90で `BattleNetworkPlayerHealth.applyHealing()` を追加し、既存チップ「リカバリー10」を実HPへ接続した。回復量は既存マスタの `RECOVERY=10` をそのまま使用し、現在HPへ10加算する。回復後HPは最大HP100でクランプするため、例えば `80→90`、`95→100` となり100を超えない。HP変化は既存の購読API経由で左上HUDへ即時反映される。HP満タン時は新たな使用制限を追加せず、従来の `useChip()` 消費フローを維持したまま実回復量0となる。撃破後の蘇生は行わない。v90は被ダメージ後の10回復・上限100・HUD即時反映の実機確認待ち。"
if anchor not in text:
    raise SystemExit('v89 status anchor not found')
text = text.replace(anchor, addition, 1)
text = text.replace('- リカバリー10の実HP回復処理。\n', '', 1)
old_next = "## 次フェーズ: リカバリー10実HP回復\n\nv82〜v85で左上HP表示とココロウィンドウ、v86で初期HP100、v87で共通被ダメージ経路、v88でテスト敵の直線単発弾まで接続し、実機で予兆・回避・命中時HP減算に問題がないことを確認済み。v89のキャノン非貫通も実機確認済み。次は既存チップ「リカバリー10」をプレイヤーHPへ接続し、使用時に最大HPを超えない範囲で10回復する処理へ進む。\n\n優先対象は以下。\n\n1. リカバリー10を `BattleNetworkPlayerHealth` へ接続し、実HPを10回復する。\n2. 回復時に左上HUDへ即時反映されることを確認する。\n3. 最大HP100を超えて回復しないことを確認する。\n4. HP満タン時のリカバリー10使用可否・消費仕様は既存仕様を確認してから確定する。\n5. その後、被弾演出・無敵時間・ノックバック・撃破処理へ拡張する。\n6. 敵AI・Wave進行へ段階的に進める。"
new_next = "## 次フェーズ: v90 リカバリー10実機確認\n\nv82〜v85で左上HP表示とココロウィンドウ、v86で初期HP100、v87〜v88で被ダメージ経路とテスト敵攻撃、v89でキャノン非貫通まで実機確認済み。v90ではリカバリー10を実HPへ接続した。次は被ダメージ後にリカバリー10を使用し、10回復・最大HP100での打ち止め・HUD即時更新を実機確認する。確認後は被弾演出・無敵時間へ進む。\n\n優先対象は以下。\n\n1. HP90以下でリカバリー10を使用し、実HPが10回復することを確認する。\n2. HP95など上限付近では100までだけ回復し、最大HPを超えないことを確認する。\n3. 回復時に左上HUDへ即時反映されることを確認する。\n4. v90確認後、被弾演出・無敵時間を設計・実装する。\n5. その後、ノックバック・撃破処理へ拡張する。\n6. 敵AI・Wave進行へ段階的に進める。"
if old_next not in text:
    raise SystemExit('next-phase block not found')
text = text.replace(old_next, new_next, 1)
status.write_text(text, encoding='utf-8')

# Remove one-time files in the same commit generated by the workflow.
Path('tools/apply_v90.py').unlink(missing_ok=True)
Path('.github/workflows/apply-v90.yml').unlink(missing_ok=True)
